name: 🗑 Clean up Vercel Deployments

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Use the deployment cleanup action to delete Vercel deployments
      - name: 🗑 Delete Vercel Deployments
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: production
          onlyRemoveDeployments: true
