name: 🗑 Clean up Vercel Deployments

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # First, delete deployments for the first environment
      - name: 🗑 Delete Deployments from first environment
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          environment: production-pleurat-pllana-hospit-frontend-developer-task
          onlyRemoveDeployments: true

      # Then, delete deployments for the second environment
      - name: 🗑 Delete Deployments from second environment
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          environment: production-pleurat-pllana-hospit-frontend-developer-task-7a6x
          onlyRemoveDeployments: true
